// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: apiservice.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplyLogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meta  *LogMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Error string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ApplyLogResponse) Reset() {
	*x = ApplyLogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apiservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyLogResponse) ProtoMessage() {}

func (x *ApplyLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyLogResponse.ProtoReflect.Descriptor instead.
func (*ApplyLogResponse) Descriptor() ([]byte, []int) {
	return file_apiservice_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyLogResponse) GetMeta() *LogMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ApplyLogResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_apiservice_proto protoreflect.FileDescriptor

var file_apiservice_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x09, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x49, 0x0a, 0x10, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x6b, 0x0a, 0x0a, 0x41,
	0x50, 0x49, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x41, 0x70, 0x70,
	0x6c, 0x79, 0x12, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x42, 0x6f, 0x64, 0x79, 0x1a,
	0x14, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0c, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x4c, 0x6f, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x75, 0x6d, 0x69, 0x6d, 0x61, 0x6b, 0x69, 0x74,
	0x6f, 0x2f, 0x72, 0x61, 0x66, 0x74, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_apiservice_proto_rawDescOnce sync.Once
	file_apiservice_proto_rawDescData = file_apiservice_proto_rawDesc
)

func file_apiservice_proto_rawDescGZIP() []byte {
	file_apiservice_proto_rawDescOnce.Do(func() {
		file_apiservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_apiservice_proto_rawDescData)
	})
	return file_apiservice_proto_rawDescData
}

var file_apiservice_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_apiservice_proto_goTypes = []interface{}{
	(*ApplyLogResponse)(nil), // 0: pb.ApplyLogResponse
	(*LogMeta)(nil),          // 1: pb.LogMeta
	(*LogBody)(nil),          // 2: pb.LogBody
	(*Command)(nil),          // 3: pb.Command
}
var file_apiservice_proto_depIdxs = []int32{
	1, // 0: pb.ApplyLogResponse.meta:type_name -> pb.LogMeta
	2, // 1: pb.APIService.Apply:input_type -> pb.LogBody
	3, // 2: pb.APIService.ApplyCommand:input_type -> pb.Command
	0, // 3: pb.APIService.Apply:output_type -> pb.ApplyLogResponse
	0, // 4: pb.APIService.ApplyCommand:output_type -> pb.ApplyLogResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apiservice_proto_init() }
func file_apiservice_proto_init() {
	if File_apiservice_proto != nil {
		return
	}
	file_command_proto_init()
	file_log_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_apiservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyLogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apiservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apiservice_proto_goTypes,
		DependencyIndexes: file_apiservice_proto_depIdxs,
		MessageInfos:      file_apiservice_proto_msgTypes,
	}.Build()
	File_apiservice_proto = out.File
	file_apiservice_proto_rawDesc = nil
	file_apiservice_proto_goTypes = nil
	file_apiservice_proto_depIdxs = nil
}
