// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: repl.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplStatus int32

const (
	ReplStatus_REPL_UNKNOWN        ReplStatus = 0
	ReplStatus_REPL_OK             ReplStatus = 1
	ReplStatus_REPL_ERR_NO_LOG     ReplStatus = 2
	ReplStatus_REPL_ERR_STALE_TERM ReplStatus = 3
	ReplStatus_REPL_ERR_INTERNAL   ReplStatus = 4
)

// Enum value maps for ReplStatus.
var (
	ReplStatus_name = map[int32]string{
		0: "REPL_UNKNOWN",
		1: "REPL_OK",
		2: "REPL_ERR_NO_LOG",
		3: "REPL_ERR_STALE_TERM",
		4: "REPL_ERR_INTERNAL",
	}
	ReplStatus_value = map[string]int32{
		"REPL_UNKNOWN":        0,
		"REPL_OK":             1,
		"REPL_ERR_NO_LOG":     2,
		"REPL_ERR_STALE_TERM": 3,
		"REPL_ERR_INTERNAL":   4,
	}
)

func (x ReplStatus) Enum() *ReplStatus {
	p := new(ReplStatus)
	*p = x
	return p
}

func (x ReplStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReplStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_repl_proto_enumTypes[0].Descriptor()
}

func (ReplStatus) Type() protoreflect.EnumType {
	return &file_repl_proto_enumTypes[0]
}

func (x ReplStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReplStatus.Descriptor instead.
func (ReplStatus) EnumDescriptor() ([]byte, []int) {
	return file_repl_proto_rawDescGZIP(), []int{0}
}

var File_repl_proto protoreflect.FileDescriptor

var file_repl_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x2a, 0x70, 0x0a, 0x0a, 0x52, 0x65, 0x70, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10,
	0x0a, 0x0c, 0x52, 0x45, 0x50, 0x4c, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x52, 0x45, 0x50, 0x4c, 0x5f, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x13, 0x0a,
	0x0f, 0x52, 0x45, 0x50, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x5f, 0x4e, 0x4f, 0x5f, 0x4c, 0x4f, 0x47,
	0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x45, 0x50, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x5f, 0x53,
	0x54, 0x41, 0x4c, 0x45, 0x5f, 0x54, 0x45, 0x52, 0x4d, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x52,
	0x45, 0x50, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x5f, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c,
	0x10, 0x04, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x75, 0x6d, 0x69, 0x6d, 0x61, 0x6b, 0x69, 0x74, 0x6f, 0x2f, 0x72, 0x61, 0x66, 0x74,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_repl_proto_rawDescOnce sync.Once
	file_repl_proto_rawDescData = file_repl_proto_rawDesc
)

func file_repl_proto_rawDescGZIP() []byte {
	file_repl_proto_rawDescOnce.Do(func() {
		file_repl_proto_rawDescData = protoimpl.X.CompressGZIP(file_repl_proto_rawDescData)
	})
	return file_repl_proto_rawDescData
}

var file_repl_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_repl_proto_goTypes = []interface{}{
	(ReplStatus)(0), // 0: pb.ReplStatus
}
var file_repl_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_repl_proto_init() }
func file_repl_proto_init() {
	if File_repl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_repl_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_repl_proto_goTypes,
		DependencyIndexes: file_repl_proto_depIdxs,
		EnumInfos:         file_repl_proto_enumTypes,
	}.Build()
	File_repl_proto = out.File
	file_repl_proto_rawDesc = nil
	file_repl_proto_goTypes = nil
	file_repl_proto_depIdxs = nil
}
